version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: trainmath
      POSTGRES_USER: trainmath
      POSTGRES_PASSWORD: trainmath_password
    ports:
      - "5432:5432"

  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             python manage.py populate_problem_types &&
             gunicorn --bind 0.0.0.0:8000 trainmath.wsgi:application"
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    environment:
      - DJANGO_PRODUCTION=1
      - POSTGRES_DB=trainmath
      - POSTGRES_USER=trainmath
      - POSTGRES_PASSWORD=trainmath_password
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - DJANGO_SECRET_KEY=your-secret-key-here
      - DJANGO_DEBUG=0
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1,0.0.0.0
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
