# Generated by Django 5.2.7 on 2025-10-04 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attempt',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.probleminstance'),
        ),
        migrations.AddField(
            model_name='probleminstance',
            name='problem_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.problemtype'),
        ),
        migrations.AddField(
            model_name='shareresult',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.attempt'),
        ),
    ]
