# Generated by Django 5.2.7 on 2025-10-04 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='probleminstance',
            name='multiple_choice_options',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
